# Generated by Django 5.2.14 on 2026-05-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=16)),
                ('activity_category', models.CharField(choices=[('STATIONARY_COMBUSTION', 'Stationary combustion'), ('MOBILE_COMBUSTION', 'Mobile combustion'), ('PURCHASED_ELECTRICITY', 'Purchased electricity'), ('BUSINESS_TRAVEL_AIR', 'Business travel — air'), ('BUSINESS_TRAVEL_HOTEL', 'Business travel — hotel'), ('BUSINESS_TRAVEL_GROUND', 'Business travel — ground')], max_length=32)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('site_code', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=32)),
                ('canonical_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('canonical_unit', models.CharField(blank=True, max_length=32)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('currency_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_fields', models.JSONField(default=dict)),
                ('normalization_notes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('FLAGGED', 'Flagged — needs attention'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked (audit-ready)')], default='PENDING', max_length=16)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.ingestionbatch')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.datasource')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='normalized', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=8)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='tenants.tenant')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='records.normalizedemissionrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('PENDING', 'Pending review'), ('FLAGGED', 'Flagged — needs attention'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked (audit-ready)')], max_length=16)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending review'), ('FLAGGED', 'Flagged — needs attention'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked (audit-ready)')], max_length=16)),
                ('analyst', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='records.normalizedemissionrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_unit', models.CharField(db_index=True, max_length=32)),
                ('canonical_unit', models.CharField(max_length=32)),
                ('factor_to_canonical', models.DecimalField(decimal_places=10, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'unique_together': {('source_unit', 'canonical_unit')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=64)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='records_aud_tenant__d9d706_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='records_nor_tenant__cc260b_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['tenant', 'activity_date'], name='records_nor_tenant__30842d_idx'),
        ),
    ]
