services:
  - type: web
    name: breathe-esg-api
    runtime: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm ci && npm run build && cd .. && cd backend && python manage.py collectstatic --noinput
    startCommand: cd backend && python manage.py migrate && python manage.py seed_demo && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: breathe-esg-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONPATH
        value: backend
      - key: DB_SSL_REQUIRE
        value: "true"

databases:
  - name: breathe-esg-db
    plan: free
